server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      allow.auto.create.topics: true
      schema.registry.url: http://localhost:8086

backend:
  kafka:
    ping-topic: hello-message-topic
    quotation-event-topic: quotation-event-topic
    consumer:
      group-id: quotation-consumer-group
      auto-offset-reset: earliest