server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      allow.auto.create.topics: true
      schema.registry.url: http://localhost:8086

backend:
  client-url:
    b-service: "http://localhost:8084"
  kafka:
    ping-topic: hello-message-topic
    quotation-event-topic: quotation-event-topic